// Code generated by "stringer -type DeployStatus project.go"; DO NOT EDIT.

package models

import "strconv"

const _DeployStatus_name = "RUNNINGSTOPPEDDEPLOYING"

var _DeployStatus_index = [...]uint8{0, 7, 14, 23}

func (i DeployStatus) String() string {
	if i < 0 || i >= DeployStatus(len(_DeployStatus_index)-1) {
		return "DeployStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeployStatus_name[_DeployStatus_index[i]:_DeployStatus_index[i+1]]
}
